Setting up build

diff --git a/ybb b/ybb
--- a/ybb
+++ b/ybb
@@ -4,7 +4,9 @@
 set -e
 
 LW_GIT_REPO=https://codeberg.org/librewolf/source.git
+LW_CLONE_TAG=121.0.1-1
 LW_CLONE_DIR=upstream-source
+YW_BUILD_DIR=yikwid-source
 
 THIS_SCRIPT_NAME="${BASH_SOURCE[0]##*/}"
 THIS_SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
@@ -31,7 +33,7 @@ show_help() {
         cd "${THIS_SCRIPT_DIR}/${LW_CLONE_DIR}"
         make help
     else
-        echo "  (must run 'make init' before passthru options can be shown)"
+        echo "  (must run '$THIS_SCRIPT_NAME init' before passthru options can be shown)"
     fi
     echo ""
 }
@@ -84,12 +86,35 @@ parse_args() {
     done
 }
 
+check_prerequisites() {
+    APT_PKGS=(python3 python3-dev python3-pip)
+    for APT_PKG in "${APT_PKG[@]}"; do
+        if ! dpkg -s "$APT_PKG" > /dev/null 2>&1; then
+            echo "ERROR: Missing required package ($APT_PKG) from: ${APT_PKG[*]}"
+            exit 1
+        fi
+    done
+}
+
 do_init() {
-    :
+    if ! upstream_cloned; then
+        git clone --single-branch --recurse-submodules --branch "$LW_CLONE_TAG" "$LW_GIT_REPO" "$LW_CLONE_DIR"
+        rsync -a "${LW_CLONE_DIR}/" "${YW_BUILD_DIR}/"
+    else
+        echo "ERROR: Already initialized. Perhaps you meant to run 'reset' or 'pull' instead?"
+        exit 1
+    fi
 }
 
 do_reset() {
-    :
+    if upstream_cloned; then
+        git -C "$LW_CLONE_DIR" reset --hard
+        # TODO settings submodule
+        # TODO add confirmation
+    else
+        echo "ERROR: Not yet initialized. Perhaps you meant to run 'init' instead?"
+        exit 1
+    fi
 }
 
 do_pull() {
@@ -110,8 +135,7 @@ do_action() {
             exit 1
         fi
 
-        cd "${THIS_SCRIPT_DIR}/${LW_CLONE_DIR}"
-        make "$PASSTHRU"
+        make -C "${THIS_SCRIPT_DIR}/${LW_CLONE_DIR}" "$PASSTHRU"
     else
         if [[ ${OPTION[DEBUG]} -eq 1 ]]; then
             set -x
@@ -121,4 +145,5 @@ do_action() {
 }
 
 parse_args "$@"
+check_prerequisites
 do_action
